micronaut:
  application:
    name: casaDoCodigoMicronaut
datasources:
  default:
    url: jdbc:mysql://localhost:3306/casaMicronaut?serverTimezone=GMT-3&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
jpa.default.properties.hibernate.hbm2ddl.auto: update
